name: build - test - push
on:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout twittify_backend
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: "~/.m2/repository"
          key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build twittifybackend
        run: mvn clean package

      - name: Generate JaCoCo badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          badges-directory: badges
          generate-branches-badge: true
          generate-summary: true

      - name: Log coverage percentages to workflow output
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push twittify:backend_latest
        uses: docker/build-push-action@v4
        with:
          context: "/home/runner/work/twittifybackend/twittifybackend"
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/twittify:backend_latest"
