name: build - test - push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout twittifyfrontend
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install
#      - name: install d2
#        run: |
#          curl -fsSL https://d2lang.com/install.sh | sh -s --
#
#      - name: create diagram definition
#        run: |
#          yarn diagram
#
#      - name: create pdf
#        run: |
#          d2 --theme=300 --dark-theme=200 -l elk --pad 100 ./diagram.d2
#
#      - name: Commit changes
#        run: |
#          git config --global user.email "simondetrois@gmail.com"
#          git config --global user.name "troissaint"
#          git add .
#          git commit --amend --no-edit
#          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
#          git push --force-with-lease
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      - name: Build twittifyfrontend
#        run: yarn build
#
#      - name: Run tests for coverage
#        run: |
#          yarn coverage --watchAll false
#
#      - name: Login to dockerhub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: build and push twittify:frontend_latest
#        uses: docker/build-push-action@v4
#        with:
#          context: "/home/runner/work/twittifyfrontend/twittifyfrontend"
#          push: true
#          tags: "${{ secrets.DOCKER_USERNAME }}/twittify:frontend_latest"
