name: build - test - push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout twittifyfrontend
        uses: actions/checkout@v3

      - name: Login to dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build and push twittify:database_latest
        uses: docker/build-push-action@v4
        with:
          context: "/home/runner/work/twittifyinfrastructure/twittifyinfrastructure/database"
          push: true
          tags: "${{ secrets.DOCKER_USERNAME }}/twittify:database_latest"
